---
# tasks file for webtunnel-ansible
- include_tasks: debian-bookworm.yml
  when:
    - ansible_distribution == 'Debian'
    - ansible_distribution_release == 'bookworm'
        
- include_tasks: debian-trixie.yml
  when:
    - ansible_distribution == 'Debian'
    - ansible_distribution_release == 'trixie'
